name: android_intent_plus
description: Flutter plugin for launching Android Intents. Not supported on iOS.
version: 4.0.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_intent_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_intent_plus

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.2
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.12.0
  mockito: ^5.4.2
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
